"""create users table

Revision ID: 6327ed0403e8
Revises: 
Create Date: 2020-09-30 14:11:26.738620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6327ed0403e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


add_user
revision = 'e38b91c06532'
down_revision = None
    ADD_notes
    revision = '6dfb606595db'
    down_revision = 'e38b91c06532'
        BLANK
        revision = 'c6abf243169f'
        down_revision = '6dfb606595db'
            REMOVE_uniqueness
            revision = '342ca557305e'
            down_revision = 'c6abf243169f'
                return_uniqueness
                revision = 'bcaa33d2cae4'
                down_revision = '342ca557305e'
        UPDATE_all_models
        revision = 'e916de74bbcb'
        down_revision = '6dfb606595db'
            ADD_is_trash
            revision = 'b22211481802'
            down_revision = 'e916de74bbcb'



